# -*- coding: utf-8 -*-
"""car_detection_yolo (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7Cma-rjsz52SO43Y3643TyTOGYM0_6X
"""

import zipfile

zip_file_path = '/content/drive/My Drive/archive (2).zip'
extract_path =  '/content/drive/My Drive/ExtractedFolder/'

#to mount google drive to google colab
from google.colab import drive
drive.mount('/content/drive')

#to get all the file paths in My drive , it's easier to generate the file paths
import os
folder_path = '/content/drive/MyDrive/'
for root, dirs, files in os.walk(folder_path):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd
import cv2
import glob

#assigning file and folder paths for test and train sets of annotations,images and labels
testdir = '/content/drive/MyDrive/archive (2)/car_data/car_data/test'
traindir = '/content/drive/MyDrive/archive (2)/car_data/car_data/train'
testannot = '/content/drive/MyDrive/archive (2)/anno_train.csv'
trainannot = '/content/drive/MyDrive/archive (2)/anno_train.csv'
carnames = '/content/drive/MyDrive/archive (2)/names.csv'
trainlabelsdir = '/content/drive/MyDrive/archive (2)/car_data/labels/train'
testlabelsdir = '/content/drive/MyDrive/archive (2)/car_data/labels/test'

df = pd.read_csv(trainannot, header=None)#whether the first row is empty
#naming the unnamed columns using rename function
df.rename(columns={0:'Image_Name',1:'Image_class',2:'xmin',3:'ymin',4:'xmax',5:'ymax'}, inplace=True)
df.head()

traindataset=traindir+'*/*' #collects the subfolders under the folder of path traindir
trainList=glob.glob(traindataset) # returns a list of all the filepaths in traindataset
trainListPaths=[]
for fileandFolder in trainList:
  List1 = fileandFolder.split('/')[-2:] #selecting only the last 2 folders of the file path
  trainListPaths.append(List1)
print(len(trainListPaths))

import os
import glob
trainListPaths = []
for folder in glob.glob(os.path.join(traindir, '*')):
    carName = os.path.basename(folder)

    image_files = glob.glob(os.path.join(folder, '*'))

    for image_path in image_files:
        imageName = os.path.basename(image_path)
        trainListPaths.append([carName, imageName])

dfTrain = pd.DataFrame(trainListPaths, columns = ['carName','imageName'])
train_df = dfTrain.merge(df, how='inner', left_on='imageName', right_on='Image_Name')

train_df.head()

df_train = train_df.copy()
unique_cars_sorted = df_train[['Image_class', 'carName']].drop_duplicates().sort_values(by='Image_class')

unique_cars_sorted.reset_index(drop=True, inplace=True)
unique_cars_sorted['carName'].unique()

annotationsTestDF = pd.read_csv(testannot, header=None)
annotationsTestDF.rename(columns={
    0: 'Image_Name',
    1: 'Image_class',
    2: 'xmin',
    3: 'ymin',
    4: 'xmax',
    5: 'ymax'
}, inplace=True)
annotationsTestDF.head()

testdataset = testdir + '*/*'
testList = glob.glob(testdataset)
testListPaths = []
for fileandFolder in testList:
  lList = fileandFolder.split('/')[-2:]
  testListPaths.append(lList)
print(len(testListPaths))

print(testListPaths[:5])

import os

testListPaths = []
for folder in glob.glob(os.path.join(testdir, '*')):
    carName = os.path.basename(folder)
    image_files = glob.glob(os.path.join(folder, '*'))

    for image_path in image_files:
        imageName = os.path.basename(image_path)
        testListPaths.append([carName, imageName])

dfTest = pd.DataFrame(testListPaths, columns = ['carName','imageName'])

test_df = dfTest.merge(annotationsTestDF, how='inner', left_on='imageName', right_on='Image_Name')

df_test = test_df.copy()
unique_cars_sorted_test = df_test[['Image_class', 'carName']].drop_duplicates().sort_values(by='Image_class')

unique_cars_sorted_test.reset_index(drop=True, inplace=True)
unique_cars_sorted_test['carName'].unique()

#os.makedirs(trainlabelsdir, exist_ok=True)
def convert_to_yolo(img_width, img_height, x1, y1, x2, y2):
    x_center = ((x1 + x2) / 2) / img_width
    y_center = ((y1 + y2) / 2) / img_height
    width = (x2 - x1) / img_width
    height = (y2 - y1) / img_height
    return x_center, y_center, width, height

# Process each row in the CSV
for _, row in train_df.iterrows():
    image_name = row['imageName']
    class_id = int(row['Image_class']) - 1  # Convert class to 0-indexed
    x1 = row['xmin']
    y1 = row['ymin']
    x2 = row['xmax']
    y2 = row['ymax']
    # Load the image to get dimensions
    folder = os.path.join(traindir,row['carName'])
    imgfile = os.path.join(folder,row['Image_Name'])
    image_path = imgfile
    image = cv2.imread(image_path)
    if image is None:
        print(f"Image {image_name} not found. Skipping.")
        continue
    img_height, img_width = image.shape[:2]

    # Convert to YOLO format
    x_center, y_center, width, height = convert_to_yolo(
        img_width, img_height, float(x1), float(y1), float(x2), float(y2)
    )

    # Write to a .txt file
    labelfolder = os.path.join(trainlabelsdir, row['carName'])
    #print(labelfolder)
    os.makedirs(labelfolder, exist_ok=True)
    label_file = os.path.join(labelfolder, image_name.replace('.jpg', '.txt'))
    with open(label_file, "w") as f:
        f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")

print("Conversion to YOLO format completed.")

def copy_file(src_path, dest_path,dataframe,):
  df_internal = dataframe.copy()
  for _, row in df_internal.iterrows():
      image_name = row['imageName']
      car_name = row['carName']
      src_file = os.path.join(src_path, car_name, image_name)
      print(src_file)
      dest_file = os.path.join(dest_path, image_name)
      shutil.copy(src_file, dest_file)

import os
import shutil
copy_path = r'/content/drive/MyDrive/archive (2)/car_data/car_data'
os.makedirs(copy_path, exist_ok=True)
train_dir=os.path.join(copy_path,'train')
test_dir=os.path.join(copy_path,'test')
os.makedirs(train_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)

copy_file(traindir,train_dir,train_df)
copy_file(testdir,test_dir,test_df)

def copy_labels(src_path, dest_path,dataframe):
  df_internal = dataframe.copy()
  for _, row in df_internal.iterrows():
    image_name = row['imageName']
    car_name = row['carName']

    src_file = os.path.join(src_path, car_name, image_name.replace('.jpg', '.txt'))
    dest_file = os.path.join(dest_path, image_name.replace('.jpg', '.txt'))
    shutil.copy(src_file, dest_file)

import os
import cv2

def convert_to_yolo(img_w, img_h, x_min, y_min, x_max, y_max):
    x_center = (x_min + x_max) / 2 / img_w
    y_center = (y_min + y_max) / 2 / img_h
    width = (x_max - x_min) / img_w
    height = (y_max - y_min) / img_h
    return x_center, y_center, width, height

def process_labels(df, base_image_dir, base_label_dir):
    # df: dataframe containing columns like ['carName', 'imageName', 'xmin', 'ymin', 'xmax', 'ymax', 'Image_class']

    for idx, row in df.iterrows():
        class_name = row['carName']          # folder/class name
        image_name = row['imageName']        # image file name
        class_id = int(row['Image_class']) - 1  # zero-index class id

        img_path = os.path.join(base_image_dir, class_name, image_name)
        label_dir = os.path.join(base_label_dir, class_name)
        os.makedirs(label_dir, exist_ok=True)

        img = cv2.imread(img_path)
        if img is None:
            print(f"Image not found: {img_path}, skipping")
            continue
        h, w = img.shape[:2]

        x_c, y_c, bw, bh = convert_to_yolo(w, h, row['xmin'], row['ymin'], row['xmax'], row['ymax'])

        label_file = os.path.join(label_dir, image_name.replace('.jpg', '.txt'))
        with open(label_file, 'w') as f:
            f.write(f"{class_id} {x_c:.6f} {y_c:.6f} {bw:.6f} {bh:.6f}\n")

    print(f"Labels converted and saved in {base_label_dir}")

# Example usage:

train_image_dir = r'/content/drive/MyDrive/archive (2)/car_data/car_data/train'
train_label_dir = r'/content/drive/MyDrive/archive (2)/car_data/labels/train'
test_image_dir = r'/content/drive/MyDrive/archive (2)/car_data/car_data/test'
test_label_dir = r'/content/drive/MyDrive/archive (2)/car_data/labels/test'

# assuming you have train_df and test_df with the columns as above:
process_labels(train_df, train_image_dir, train_label_dir)
process_labels(test_df, test_image_dir, test_label_dir)

import os
import shutil
copy_path_labels = r'/content/drive/MyDrive/archive (2)/car_data/labels'
os.makedirs(copy_path_labels, exist_ok=True)
train_dir_label=os.path.join(copy_path_labels,'train')
test_dir_label=os.path.join(copy_path_labels,'test')
os.makedirs(train_dir_label, exist_ok=True)
os.makedirs(test_dir_label, exist_ok=True)

copy_labels(trainlabelsdir,train_dir_label,train_df)
copy_labels(testlabelsdir,test_dir_label,test_df)

!pip install ultralytics opencv-python-headless pandas matplotlib

import os
print(os.path.exists("/content/drive/MyDrive/archive (2)/car_data/car_data/train"))
print(os.path.exists("/content/drive/MyDrive/archive (2)/car_data/car_data/test"))

import os

img_dir = "/content/drive/MyDrive/archive (2)/car_data/car_data/test"
label_dir = "/content/drive/MyDrive/archive (2)/car_data/labels/test"

img_files = sorted([f[:-4] for f in os.listdir(img_dir) if f.endswith('.jpg')])
label_files = sorted([f[:-4] for f in os.listdir(label_dir) if f.endswith('.txt')])

missing_labels = set(img_files) - set(label_files)
print(f"Total images: {len(img_files)}")
print(f"Total labels: {len(label_files)}")
print(f"Missing labels for: {len(missing_labels)} images")

for f in missing_labels:
    open(os.path.join(label_dir, f + '.txt'), 'w').close()

from ultralytics import YOLO
#from pathlib import Path
# Load pre-trained YOLOv8 model
model = YOLO("yolov8n.pt")
rel_path = r"/content/drive/MyDrive/archive (2)/car_data/data.yaml"
#full_path = Path(rel_path).resolve()
# Train the model
results = model.train(
    data=rel_path,
    epochs=50,
    imgsz=640,
    batch=16)

import glob
from IPython.display import Image, display
# Load the trained model
class_names = ['AM General Hummer SUV 2000','Acura RL Sedan 2012','Acura TL Sedan 2012','Acura TL Type-S 2008','Acura TSX Sedan 2012','Acura Integra Type R 2001',
        'Acura ZDX Hatchback 2012','Aston Martin V8 Vantage Convertible 2012','Aston Martin V8 Vantage Coupe 2012','Aston Martin Virage Convertible 2012',
        'Aston Martin Virage Coupe 2012','Audi RS 4 Convertible 2008','Audi A5 Coupe 2012','Audi TTS Coupe 2012','Audi R8 Coupe 2012','Audi V8 Sedan 1994',
        'Audi 100 Sedan 1994','Audi 100 Wagon 1994','Audi TT Hatchback 2011','Audi S6 Sedan 2011','Audi S5 Convertible 2012','Audi S5 Coupe 2012',
        'Audi S4 Sedan 2012','Audi S4 Sedan 2007','Audi TT RS Coupe 2012','BMW ActiveHybrid 5 Sedan 2012','BMW 1 Series Convertible 2012',
        'BMW 1 Series Coupe 2012','BMW 3 Series Sedan 2012','BMW 3 Series Wagon 2012','BMW 6 Series Convertible 2007','BMW X5 SUV 2007','BMW X6 SUV 2012',
        'BMW M3 Coupe 2012','BMW M5 Sedan 2010','BMW M6 Convertible 2010','BMW X3 SUV 2012','BMW Z4 Convertible 2012',
        'Bentley Continental Supersports Conv. Convertible 2012','Bentley Arnage Sedan 2009','Bentley Mulsanne Sedan 2011','Bentley Continental GT Coupe 2012',
        'Bentley Continental GT Coupe 2007','Bentley Continental Flying Spur Sedan 2007','Bugatti Veyron 16.4 Convertible 2009','Bugatti Veyron 16.4 Coupe 2009',
        'Buick Regal GS 2012','Buick Rainier SUV 2007','Buick Verano Sedan 2012','Buick Enclave SUV 2012','Cadillac CTS-V Sedan 2012','Cadillac SRX SUV 2012',
        'Cadillac Escalade EXT Crew Cab 2007','Chevrolet Silverado 1500 Hybrid Crew Cab 2012','Chevrolet Corvette Convertible 2012','Chevrolet Corvette ZR1 2012',
        'Chevrolet Corvette Ron Fellows Edition Z06 2007','Chevrolet Traverse SUV 2012','Chevrolet Camaro Convertible 2012','Chevrolet HHR SS 2010',
        'Chevrolet Impala Sedan 2007','Chevrolet Tahoe Hybrid SUV 2012','Chevrolet Sonic Sedan 2012','Chevrolet Express Cargo Van 2007',
        'Chevrolet Avalanche Crew Cab 2012','Chevrolet Cobalt SS 2010','Chevrolet Malibu Hybrid Sedan 2010','Chevrolet TrailBlazer SS 2009',
        'Chevrolet Silverado 2500HD Regular Cab 2012','Chevrolet Silverado 1500 Classic Extended Cab 2007','Chevrolet Express Van 2007',
        'Chevrolet Monte Carlo Coupe 2007','Chevrolet Malibu Sedan 2007','Chevrolet Silverado 1500 Extended Cab 2012','Chevrolet Silverado 1500 Regular Cab 2012',
        'Chrysler Aspen SUV 2009','Chrysler Sebring Convertible 2010','Chrysler Town and Country Minivan 2012','Chrysler 300 SRT-8 2010',
        'Chrysler Crossfire Convertible 2008','Chrysler PT Cruiser Convertible 2008','Daewoo Nubira Wagon 2002','Dodge Caliber Wagon 2012',
        'Dodge Caliber Wagon 2007','Dodge Caravan Minivan 1997','Dodge Ram Pickup 3500 Crew Cab 2010','Dodge Ram Pickup 3500 Quad Cab 2009',
        'Dodge Sprinter Cargo Van 2009','Dodge Journey SUV 2012','Dodge Dakota Crew Cab 2010','Dodge Dakota Club Cab 2007','Dodge Magnum Wagon 2008',
        'Dodge Challenger SRT8 2011','Dodge Durango SUV 2012','Dodge Durango SUV 2007','Dodge Charger Sedan 2012','Dodge Charger SRT-8 2009',
        'Eagle Talon Hatchback 1998','FIAT 500 Abarth 2012','FIAT 500 Convertible 2012','Ferrari FF Coupe 2012','Ferrari California Convertible 2012',
        'Ferrari 458 Italia Convertible 2012','Ferrari 458 Italia Coupe 2012','Fisker Karma Sedan 2012','Ford F-450 Super Duty Crew Cab 2012',
        'Ford Mustang Convertible 2007','Ford Freestar Minivan 2007','Ford Expedition EL SUV 2009','Ford Edge SUV 2012','Ford Ranger SuperCab 2011',
        'Ford GT Coupe 2006','Ford F-150 Regular Cab 2012','Ford F-150 Regular Cab 2007','Ford Focus Sedan 2007','Ford E-Series Wagon Van 2012',
        'Ford Fiesta Sedan 2012','GMC Terrain SUV 2012','GMC Savana Van 2012','GMC Yukon Hybrid SUV 2012','GMC Acadia SUV 2012','GMC Canyon Extended Cab 2012',
        'Geo Metro Convertible 1993','HUMMER H3T Crew Cab 2010','HUMMER H2 SUT Crew Cab 2009','Honda Odyssey Minivan 2012','Honda Odyssey Minivan 2007',
        'Honda Accord Coupe 2012','Honda Accord Sedan 2012','Hyundai Veloster Hatchback 2012','Hyundai Santa Fe SUV 2012','Hyundai Tucson SUV 2012',
        'Hyundai Veracruz SUV 2012','Hyundai Sonata Hybrid Sedan 2012','Hyundai Elantra Sedan 2007','Hyundai Accent Sedan 2012','Hyundai Genesis Sedan 2012',
        'Hyundai Sonata Sedan 2012','Hyundai Elantra Touring Hatchback 2012','Hyundai Azera Sedan 2012','Infiniti G Coupe IPL 2012','Infiniti QX56 SUV 2011',
        'Isuzu Ascender SUV 2008','Jaguar XK XKR 2012','Jeep Patriot SUV 2012','Jeep Wrangler SUV 2012','Jeep Liberty SUV 2012','Jeep Grand Cherokee SUV 2012',
        'Jeep Compass SUV 2012','Lamborghini Reventon Coupe 2008','Lamborghini Aventador Coupe 2012','Lamborghini Gallardo LP 570-4 Superleggera 2012',
        'Lamborghini Diablo Coupe 2001','Land Rover Range Rover SUV 2012','Land Rover LR2 SUV 2012','Lincoln Town Car Sedan 2011',
        'MINI Cooper Roadster Convertible 2012','Maybach Landaulet Convertible 2012','Mazda Tribute SUV 2011','McLaren MP4-12C Coupe 2012',
        'Mercedes-Benz 300-Class Convertible 1993','Mercedes-Benz C-Class Sedan 2012','Mercedes-Benz SL-Class Coupe 2009','Mercedes-Benz E-Class Sedan 2012',
        'Mercedes-Benz S-Class Sedan 2012','Mercedes-Benz Sprinter Van 2012','Mitsubishi Lancer Sedan 2012','Nissan Leaf Hatchback 2012',
        'Nissan NV Passenger Van 2012','Nissan Juke Hatchback 2012','Nissan 240SX Coupe 1998','Plymouth Neon Coupe 1999','Porsche Panamera Sedan 2012',
        'Ram C-V Cargo Van Minivan 2012','Rolls-Royce Phantom Drophead Coupe Convertible 2012','Rolls-Royce Ghost Sedan 2012','Rolls-Royce Phantom Sedan 2012',
        'Scion xD Hatchback 2012','Spyker C8 Convertible 2009','Spyker C8 Coupe 2009','Suzuki Aerio Sedan 2007','Suzuki Kizashi Sedan 2012',
        'Suzuki SX4 Hatchback 2012','Suzuki SX4 Sedan 2012','Tesla Model S Sedan 2012','Toyota Sequoia SUV 2012','Toyota Camry Sedan 2012',
        'Toyota Corolla Sedan 2012','Toyota 4Runner SUV 2012','Volkswagen Golf Hatchback 2012','Volkswagen Golf Hatchback 1991','Volkswagen Beetle Hatchback 2012',
        'Volvo C30 Hatchback 2012','Volvo 240 Sedan 1993','Volvo XC90 SUV 2007','smart fortwo Convertible 2012']

model = YOLO("/content/runs/detect/train4/weights/best.pt")
image_path = "/content/drive/My Drive/archive (2)/car_data/car_data/test/Toyota Camry Sedan 2012/06540.jpg"
# Run inference on an image
results = model.predict(image_path, save=True)
detections = results[0].boxes



# Define the base path where the folders are located
base_path = '/content/runs/detect/'

# List all directories that start with 'predict' in the base path
subfolders = [os.path.join(base_path, d) for d in os.listdir(base_path)
              if os.path.isdir(os.path.join(base_path, d)) and d.startswith('predict')]

# Find the latest folder by modification time
latest_folder = max(subfolders, key=os.path.getmtime)

image_paths = glob.glob(f'{latest_folder}/*.jpg')[:3]

# Display each image
for image_path in image_paths:
    display(Image(filename=image_path, width=600))
    print("\n")

import glob
from IPython.display import Image, display

# Find the latest predict folder
predict_folders = sorted(glob.glob('/content/runs/detect/predict*'), key=os.path.getmtime)
latest_folder = predict_folders[-1]  # most recent

# Get the output image(s)
output_images = glob.glob(f"{latest_folder}/*.jpg")

# Show them
for img_path in output_images:
    display(Image(filename=img_path, width=600))

results = model.predict(image_path, save=True)